### ISSUE TITLE
roll dice

### ISSUE THREAD

**Issue by bibli0phile** [STEP-tw/ludo-dvamps#12]
As a _player_

I want to _roll the dice_

So that I may _know my move to go further_

**Additional Details**

players will be informed by the dice number

**Dependencies**

it will be dependent on the other players of the game, current player's turn and move coin

**Acceptance Criteria**

- [x] Criteria 1
  - When _the current player roll the dice_
  - Then _players should be informed of the exact move he/she gets_

- [x] Criteria 2
  - When _player roll the dice_
  - Then _dice should give a move only from 1,2,3,4,5,6_

- [x] Criteria 3
  - When _player(not current) roll the dice_
  - Then _dice shouldn't move for that player and inform only that player about it_

- [x] Criteria 4
  - When _player rolls the dice_
  - Then _all the players should be notified of the move current player got_

- [x] Criteria 5
  - When _someone not playing a game asked for roll dice_
  - Then _should be send forbidden zone response_

- [x] Criteria 6
  - When _a player asked for rolling dice  before game started_
  - Then _he/she should be informed of appropriate error message_

**Comment by ashishkujoy** [comment]
Dice should not be rolled if game is not started.
Dice status should be given to only those player who are playing that particular game.
Write test for dice status.

**Comment by TPKalyan** [comment]
- create a button to roll dice
- enable it when it's their turn
- in remaining time it should be disabled
