### ISSUE TITLE
board page

### ISSUE THREAD

**Issue by bibli0phile** [STEP-tw/ludo-dvamps#20]
As a _player_

I want to _know where to play_

So that I may _know what to do_

**Acceptance Criteria**

- [x] Criteria 1
  - When _game starts_
  - Then _player should be able to see all(board, dice, activity log space_

**Comment by ashishkujoy** [comment]
When player name is having character length more than 8 its causing css problem.

**Comment by TPKalyan** [comment]
**Changes**:
- star size in safe position is a bit big we need to reduce the size
- highlighting the movable coins is looking a bit awkward 
- board also need some changes
- player names on the board are looking like a button
